### ISSUE TITLE
Implement watch list

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone#13]
### Value Statement
As a user i 
I want a page where i can see a watch list
so that I know which books i want to read next
### Description
I can add and delete books from this watch list. Adding works from a bestlist page. The Deletion works from the watch list itself.

### Acceptance Criteria

- [x] the user clicks in the navbar on "watchlist" and gets redirected
- [x] on the watchlist the user can add and delete titles.

### Tasks
- [x] create watchlist table
- [x] create a button in frontend
- [x] create path from frontend to axios
- [x] create path from table to Restcontroller
