### ISSUE TITLE
Bookcovers add to best list

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone#17]
### Value Statement
As a user i 
I want to see a book cover to every book
so that I can get a clearer picture of the content
### Description
I see a book cover next to the book in the list.

### Acceptance Criteria

- [ ] the user sees a book cover to every book in a best list and in the watch list.

### Tasks
- [ ] save isbn from nyt API
- [ ] implement Cover API in FrontEnd with Axios REe.
- [ ] create path from frontend to axios
