### ISSUE TITLE
User can sign in

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone#2]
### Value Statement
As a user i 
I want a page where i can sign in
so that i can reach my homepage
### Description
The welcome page has a heading saying "Willkommen" and a input field for signing in.

### Acceptance Criteria

- [x] the user can log in with credentials (user:"user",password:"test")
- [x] after login the user sees demo homepage(protected route)

### Tasks
- [x] create the necessary directories
- [x] create one page which includes the components header, body and footer
- [x] create the sign in page
- [x] create the home page (protected route)
- [x] connect all pages via react router
- [x] integrate database with a hard coded username and password
- [x] create protected route for demo homepage
- [x] user can Logout
