### ISSUE TITLE
Schöneres UI

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone#8]
### Value Statement
As a user i want a webpage
which looks appealing
so that i spend more time on it
### Description
....

### Acceptance Criteria

- [ ] pictures are rendered symmetrical
- [ ] no margin between background and browser

### Tasks
- [ ] remove non mobile version in navbar
- [ ] ...
- [ ] ...
