### ISSUE TITLE
User sees a list of books

### ISSUE THREAD

**Issue by RobRobRoberto** [RobRobRoberto/Capstone#9]
### Value Statement
As a user i 
I want a page where i can see a best list
so that I have a benefit of using the app
### Description
The best list page contains a list of books with a picture of the respective book, the name of the author and the name of the book.

### Acceptance Criteria

- [ ] the user clicks on one of the tiles on the homepage and gets redirected to the respective best list
- [ ] on the best list list he gets a clear picture of the best books 

### Tasks
- [x] create a new table
- [x] fill it with an api
- [ ] create a new table
- [ ] fill it with web scrapping
- [x] create the respective route to the front end
- [x] have it rendered on the frontend
- [ ] make it look good
